import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core"
import type { FieldDefinition, ModelDefinition } from "@base-auth/core/adapter"

export interface GenerateSqliteSchemaOptions {
  /** @default false */
  usePlural?: boolean
  /** Naming convention for generated DB columns. @default "snake_case" */
  columnCase?: "snake_case" | "camelCase"
}

function toSnakeCase(key: string) {
  return key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`)
}

function columnName(key: string, columnCase: "snake_case" | "camelCase") {
  return columnCase === "camelCase" ? key : toSnakeCase(key)
}

function buildColumn(
  fieldName: string,
  field: FieldDefinition,
  columnCase: "snake_case" | "camelCase",
  tables: Record<string, any>,
) {
  const name = columnName(fieldName, columnCase)
  let column: any
  switch (field.type) {
    case "string":
      column = text(name)
      break
    case "number":
      column = integer(name)
      break
    case "boolean":
      column = integer(name, { mode: "boolean" })
      break
    case "date":
      column = integer(name, { mode: "timestamp_ms" })
      break
  }
  if (fieldName === "id") column = column.primaryKey()
  else {
    if (field.required) column = column.notNull()
    // a primary key is already implicitly unique - skip the redundant index
    if (field.unique) column = column.unique()
  }
  if (field.references) {
    const ref = field.references
    column = column.references(() => tables[ref.model][ref.field])
  }
  return column
}

/**
 * Turns declarative `ModelDefinition`s (contributed by core + whichever
 * plugins are enabled) into real, *live* Drizzle SQLite table objects, in
 * memory. This is what ephemeral test fixtures use (see `shared/roles/test`,
 * `shared/username/test`) - not what a real app's `schema.ts` should call.
 *
 * For a real app, use `bunx @base-auth/adapter-drizzle generate` instead
 * (see `generateSqliteSchemaSource` below) - it writes an actual file you
 * commit and can hand-edit (rename columns, add fields, change types),
 * rather than re-deriving the same fixed shape from this function on every
 * boot with no way to customize it beyond `columnCase`/`usePlural`.
 *
 * Return type is intentionally loose (`Record<string, any>`) - full type
 * inference the way hand-written Drizzle schemas get isn't preserved for
 * dynamically generated tables.
 */
export function generateSqliteSchema(
  models: Record<string, ModelDefinition>,
  opts: GenerateSqliteSchemaOptions = {},
): Record<string, any> {
  const columnCase = opts.columnCase ?? "snake_case"
  const usePlural = opts.usePlural ?? false
  const tables: Record<string, any> = {}

  for (const [modelName, model] of Object.entries(models)) {
    const tableName = usePlural ? `${modelName}s` : modelName
    const columns: Record<string, any> = {}
    for (const [fieldName, field] of Object.entries(model.fields)) {
      columns[fieldName] = buildColumn(fieldName, field, columnCase, tables)
    }
    tables[modelName] = sqliteTable(tableName, columns)
  }

  return tables
}

function buildColumnSource(
  fieldName: string,
  field: FieldDefinition,
  columnCase: "snake_case" | "camelCase",
): string {
  const name = columnName(fieldName, columnCase)
  const typeCall =
    field.type === "string"
      ? `text("${name}")`
      : field.type === "number"
        ? `integer("${name}")`
        : field.type === "boolean"
          ? `integer("${name}", { mode: "boolean" })`
          : `integer("${name}", { mode: "timestamp_ms" })`

  let source = typeCall
  if (fieldName === "id") {
    source += ".primaryKey()"
  } else {
    if (field.required) source += ".notNull()"
    if (field.unique) source += ".unique()"
  }
  if (field.references) {
    source += `.references(() => ${field.references.model}.${field.references.field})`
  }
  return source
}

/**
 * The codegen counterpart to `generateSqliteSchema` - instead of live
 * Drizzle objects, emits the literal TypeScript source of an ordinary,
 * hand-editable schema file. `bunx @base-auth/adapter-drizzle generate`
 * (see `cli.ts`) is what actually calls this and writes the result to disk;
 * this function itself is pure (models in, source string out) so it's easy
 * to test without touching the filesystem.
 */
export function generateSqliteSchemaSource(
  models: Record<string, ModelDefinition>,
  opts: GenerateSqliteSchemaOptions = {},
): string {
  const columnCase = opts.columnCase ?? "snake_case"
  const usePlural = opts.usePlural ?? false

  const lines = [
    "// Generated by `bunx @base-auth/adapter-drizzle generate` - this is a",
    "// starting point, not a fixed contract. Rename columns, add fields,",
    "// change types - it's your file from here. Re-running `generate`",
    "// overwrites it, so treat this like `drizzle-kit generate`'s output:",
    "// generate once, then own it.",
    `import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core"`,
    "",
  ]

  for (const [modelName, model] of Object.entries(models)) {
    const tableName = usePlural ? `${modelName}s` : modelName
    lines.push(`export const ${modelName} = sqliteTable("${tableName}", {`)
    for (const [fieldName, field] of Object.entries(model.fields)) {
      lines.push(
        `  ${fieldName}: ${buildColumnSource(fieldName, field, columnCase)},`,
      )
    }
    lines.push("})", "")
  }

  const modelNames = Object.keys(models)
  lines.push(
    "// Convenience bundle for constructing `db`/the adapter - drizzle()",
    "// and drizzleAdapter() both take this shape. Feel free to inline the",
    "// individual table imports instead and drop this if you'd rather.",
    `export const schema = { ${modelNames.join(", ")} }`,
  )

  return lines.join("\n")
}
