// Generated by `bunx @base-auth/adapter-drizzle generate` - this is a
// starting point, not a fixed contract. Rename columns, add fields,
// change types - it's your file from here. Re-running `generate`
// overwrites it, so treat this like `drizzle-kit generate`'s output:
// generate once, then own it.
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core"

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  email: text("email"),
  preferredName: text("preferred_name"),
  avatar: text("avatar"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
})

export const account = sqliteTable("account", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull().references(() => user.id),
  providerId: text("provider_id").notNull(),
  accountId: text("account_id").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
})

export const username = sqliteTable("username", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull().unique().references(() => user.id),
  username: text("username").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
})

export const role = sqliteTable("role", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull().unique().references(() => user.id),
  role: text("role").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
})

// Convenience bundle for constructing `db`/the adapter - drizzle()
// and drizzleAdapter() both take this shape. Feel free to inline the
// individual table imports instead and drop this if you'd rather.
export const schema = { user, account, username, role }